//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalAccounting.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AccountingEntities : DbContext
    {
        public AccountingEntities()
            : base("name=AccountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<GetExpenseRecords_Result> GetExpenseRecords(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetExpenseRecords_Result>("GetExpenseRecords", startParameter, endParameter);
        }
    
        public virtual ObjectResult<GetIncomeRecords_Result> GetIncomeRecords(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetIncomeRecords_Result>("GetIncomeRecords", startParameter, endParameter);
        }
    
        public virtual ObjectResult<NetProfit_Result> NetProfit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NetProfit_Result>("NetProfit");
        }
    
        public virtual ObjectResult<Profit_Result> Profit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Profit_Result>("Profit");
        }
    
        public virtual ObjectResult<selectcategory_Result> selectcategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selectcategory_Result>("selectcategory");
        }
    }
}
