//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalAccounting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public string Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string CategoryId { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public string ExpenseId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Expense Expense { get; set; }
    }
}
